import { useState, useEffect, useRef } from "react";
import { supabase } from "./lib/supabase";
import { trackLead } from "./lib/track";
import board from "./board.json";

// ─── TOKENS ("Apricot Terminal", see brand card) ──────────
const C = {
  paper:"#FFF4E9", apricot:"#FFC290", blush:"#FFE3C7",
  ember:"#E2743B", emberHi:"#FF9B4A",
  ink:"#201812", terminal:"#10151E",
  mint:"#00E6A0", mintText:"#0B7A57",
  warn:"#FFB800", danger:"#FF5C5C",
};
const inkA = a => `rgba(32,24,18,${a})`;
const whiteA = a => `rgba(255,255,255,${a})`;

// ─── THIS WEEK'S BOARD (generated by the research agent, src/board.json) ──
const BOARD = { week: board.week, top: board.top, rows: board.rows };

const FAQS = [
  { q:"Who picks these products?", a:"An automated research agent. It scores every product the same way, every week. No manual picks, no sponsored placement." },
  { q:"Where does the data come from?", a:"Five source types: supplier bestseller lists, TikTok trend signals, search trend data, seller communities, marketplace listings. A product makes the board only when two independent sources say it's rising." },
  { q:"How are products scored?", a:"Five checks, 0–5 each: rise speed, margin, competition, EU fit, repeat purchases. The board shows the score and the reasoning." },
  { q:"Why EU only?", a:"Most product research tools rank US winners. Different suppliers, different shipping times, different VAT. The board scores EU demand against EU supply." },
  { q:"Is it free?", a:"Yes, during early access. A paid full board comes later. Early members keep a founder price." },
  { q:"What about my email?", a:"Your email is stored securely and used only to contact you about DropSynth early access. We never sell or share it. You can request deletion at any time — see our privacy policy." },
];

// ─── HELPERS ──────────────────────────────────────────────
function smoothScroll(id) {
  const el = document.getElementById(id);
  if (!el) return;
  const root = document.scrollingElement || document.documentElement;
  const start = root.scrollTop;
  const target = el.getBoundingClientRect().top + start - 64;
  const dist = target - start;
  const dur = 420;
  let t0 = null;
  function step(ts) {
    if (!t0) t0 = ts;
    const p = Math.min((ts - t0) / dur, 1);
    root.scrollTop = start + dist * (1 - Math.pow(1 - p, 3));
    if (p < 1) requestAnimationFrame(step);
  }
  requestAnimationFrame(step);
}

function useIsMobile() {
  const [mob, setMob] = useState(() => window.innerWidth <= 680);
  useEffect(() => {
    const fn = () => setMob(window.innerWidth <= 680);
    window.addEventListener("resize", fn);
    return () => window.removeEventListener("resize", fn);
  }, []);
  return mob;
}

// once-only scroll reveal
function Reveal({ children, style }) {
  const ref = useRef(null);
  const [inView, setInView] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    if (typeof IntersectionObserver === "undefined" ||
        window.matchMedia("(prefers-reduced-motion: reduce)").matches) { setInView(true); return; }
    // anything already at or above the viewport reveals immediately — the observer
    // only stages elements still below the fold
    if (el.getBoundingClientRect().top < window.innerHeight * 0.95) { setInView(true); return; }
    const ob = new IntersectionObserver(([e]) => {
      if (e.isIntersecting) { setInView(true); ob.disconnect(); }
    }, { rootMargin: "0px 0px -10% 0px" });
    ob.observe(el);
    return () => ob.disconnect();
  }, []);
  return <div ref={ref} className={`rv${inView ? " rv-in" : ""}`} style={style}>{children}</div>;
}

// ─── SMALL COMPONENTS ─────────────────────────────────────
const Eyebrow = ({ children, color = inkA(.62), style = {} }) => (
  <div className="mono" style={{fontSize:12,letterSpacing:"0.14em",textTransform:"uppercase",color,...style}}>{children}</div>
);

function Btn({ children, onClick, disabled, full, size="md", variant="primary", style={} }) {
  const sz = { sm:{height:44,padding:"0 22px",fontSize:14}, md:{height:52,padding:"0 28px",fontSize:15}, lg:{height:54,padding:"0 30px",fontSize:16} }[size];
  const v = {
    primary:{background:`linear-gradient(90deg,${C.emberHi},${C.ember})`,color:C.paper,border:"none",boxShadow:`0 10px 24px rgba(226,116,59,.35)`,fontWeight:600},
    ink:{background:C.ink,color:C.paper,border:"none",fontWeight:500},
  }[variant];
  return (
    <button className="hv-btn" onClick={disabled?undefined:onClick} disabled={disabled} style={{
      ...sz,...v,display:"inline-flex",alignItems:"center",justifyContent:"center",gap:8,
      borderRadius:999,cursor:disabled?"not-allowed":"pointer",opacity:disabled?.6:1,
      fontFamily:"'Space Grotesk',sans-serif",width:full?"100%":"auto",...style,
    }}>{children}</button>
  );
}

const Spinner = () => <div style={{width:14,height:14,border:`2px solid ${whiteA(.3)}`,borderTopColor:C.paper,borderRadius:"50%",animation:"spin .7s linear infinite",flexShrink:0}}/>;

function ScoreBars({ score }) {
  const bars = Math.max(1, Math.round((score / 25) * 4));
  return (
    <div aria-hidden style={{display:"flex",alignItems:"flex-end",gap:3,height:18,flexShrink:0}}>
      {[8,12,16,18].map((h,i)=>(
        <div key={i} style={{width:4,height:h,borderRadius:2,background:i<bars?C.ember:"rgba(226,116,59,.3)"}}/>
      ))}
    </div>
  );
}

const LockBadge = () => (
  <span className="mono" style={{display:"inline-flex",alignItems:"center",height:24,padding:"0 12px",borderRadius:999,background:C.terminal,fontSize:10,letterSpacing:"0.12em",color:C.mint,flexShrink:0}}>EARLY ACCESS</span>
);

const MacDots = ({ label, labelColor }) => (
  <div style={{display:"flex",alignItems:"center",gap:8,padding:"14px 18px",borderBottom:`1px solid ${whiteA(.07)}`}}>
    {[C.danger,C.warn,C.mint].map(c=><div key={c} style={{width:10,height:10,borderRadius:"50%",background:c}}/>)}
    <span className="mono" style={{marginLeft:10,fontSize:11,letterSpacing:"0.1em",color:labelColor||whiteA(.45)}}>{label}</span>
  </div>
);

// the terminal prints this Monday's actual top-5: #1 open, #2–#5 redacted
const TERM_ROWS = board.termRows;

function HeroTerminal({ mob }) {
  return (
    <div className="hv-term" style={{
      width:"100%",maxWidth:560,borderRadius:16,background:C.terminal,
      border:`1px solid rgba(0,230,160,.25)`,boxShadow:`0 30px 60px ${inkA(.28)}`,
      transform:mob?"none":"perspective(1200px) rotateY(-6deg) rotateX(2deg)",
    }}>
      <MacDots label={`dropsynth board — ${BOARD.week}`}/>
      <div className="mono" style={{display:"flex",flexDirection:"column",gap:10,padding:mob?"18px 16px 22px":"22px 22px 26px",fontSize:mob?11.5:13,lineHeight:1.5,color:C.mint}}>
        <span className="ds-type" style={{animationDelay:"300ms"}}>&gt; monday scan · 5 source types</span>
        <span className="ds-type" style={{animationDelay:"1400ms"}}>&gt; scored 0–25 · two-signal rule</span>
        <span className="ds-type" style={{animationDelay:"2500ms",color:whiteA(.55)}}>&gt; board {BOARD.week} · printing…</span>
        <div style={{height:1,background:whiteA(.09),margin:"4px 0"}}/>
        {TERM_ROWS.map((r,i)=>(
          <div key={r.rank} className="ds-row" style={{display:"flex",gap:12,alignItems:"baseline",animationDelay:`${3400+i*160}ms`}}>
            <span style={{width:26,flexShrink:0,color:r.open?C.mint:whiteA(.45)}}>#{r.rank}</span>
            <span style={{flexGrow:1,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",color:r.open?"#FFF4E9":whiteA(.3),letterSpacing:r.open?0:"-0.06em"}}>{r.label}</span>
            <span style={{flexShrink:0,color:r.open?C.mint:whiteA(.45)}}>{r.score}/25</span>
          </div>
        ))}
        <span className="ds-row" style={{display:"flex",color:whiteA(.55),animationDelay:"4300ms",marginTop:2}}>&gt; + five more · unlock free<span className="ds-cursor" style={{color:C.mint}}>_</span></span>
      </div>
    </div>
  );
}

// real niches from this week's board
const NICHES = board.niches;
function NicheTicker() {
  const items = [...NICHES, ...NICHES];
  return (
    <div style={{display:"flex",alignItems:"center",background:C.blush,borderTop:`1px solid ${inkA(.08)}`,borderBottom:`1px solid ${inkA(.08)}`}}>
      <span className="mono" style={{flexShrink:0,padding:"10px 18px",fontSize:11,letterSpacing:"0.14em",fontWeight:700,borderRight:`1px solid ${inkA(.12)}`}}>ON THE BOARD THIS WEEK</span>
      <div style={{overflow:"hidden",flexGrow:1,padding:"10px 0"}}>
      <div className="ds-ticker mono" style={{fontSize:11,letterSpacing:"0.14em"}}>
        {items.map((n,i)=>(
          <span key={i} style={{color:inkA(.62)}}>
            <span style={{color:C.ember}}>▲ </span>{n}
            <span style={{color:inkA(.3)}}>{"  ·  "}</span>
          </span>
        ))}
      </div>
      </div>
    </div>
  );
}

// ─── WAITLIST FORM (real Supabase; success unlocks board) ─
function WaitlistForm({ onSuccess }) {
  const [email, setEmail] = useState("");
  const [consent, setConsent] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const submit = async () => {
    const e = email.trim().toLowerCase();
    if (!e) { setError("Email is required."); return; }
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)) { setError("Enter a valid email."); return; }
    if (!consent) { setError("Please accept the privacy terms."); return; }
    if (!supabase) { setError("Backend not configured yet — see .env.example."); return; }

    setError(""); setLoading(true);
    const { error: dbError } = await supabase
      .from("waitlist")
      .insert({ email: e, name: null, plan: "board", source: "landing" });

    setLoading(false);
    if (dbError && dbError.code !== "23505") {
      setError("Something went wrong. Try again.");
      return;
    }
    // duplicate email (23505) still unlocks — they're already on the list
    trackLead("board");
    onSuccess();
  };

  return (
    <div style={{display:"flex",flexDirection:"column",gap:12}}>
      <div style={{display:"flex",gap:12,flexWrap:"wrap"}}>
        <input
          style={{
            flex:"1 1 220px",height:52,padding:"0 18px",borderRadius:12,
            background:whiteA(.06),border:`1px solid ${whiteA(.14)}`,color:C.paper,
            fontSize:14,fontFamily:"'Space Mono',monospace",outline:"none",minWidth:0,
          }}
          placeholder="you@store.eu" type="email" value={email} aria-label="Email"
          onChange={e=>setEmail(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} autoComplete="email"
        />
        <Btn onClick={submit} disabled={loading} style={{flexShrink:0}}>
          {loading ? <><Spinner/> Joining…</> : "Get the full board"}
        </Btn>
      </div>
      <label style={{display:"flex",gap:8,alignItems:"flex-start",fontSize:12,color:whiteA(.6),cursor:"pointer",lineHeight:1.5}}>
        <input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}
          style={{marginTop:2,accentColor:C.mint,flexShrink:0,width:16,height:16}}/>
        <span>I agree that DropSynth stores my email to contact me about early access. I can request deletion anytime. <a href="/privacy.html" target="_blank" rel="noreferrer" style={{color:C.mint}}>Privacy policy</a></span>
      </label>
      {error && <div style={{fontSize:13,color:C.danger}}>{error}</div>}
      <span className="mono" style={{fontSize:11,letterSpacing:"0.1em",color:"rgba(0,230,160,.7)"}}>NO CARD. NO SPAM. FREE NOW · FOUNDER PRICE LATER.</span>
    </div>
  );
}

// ─── BOARD ROWS ───────────────────────────────────────────
function BoardRow({ row, unlocked, mob }) {
  if (!unlocked && row.rank <= 5) {
    return (
      <div style={{display:"flex",alignItems:"center",gap:mob?12:18,height:56,padding:mob?"0 14px":"0 22px",borderRadius:14,background:"rgba(255,244,233,.6)"}}>
        <span className="mono" style={{fontWeight:700,fontSize:14,width:32,flexShrink:0}}>#{row.rank}</span>
        <div style={{flexGrow:1,height:12,borderRadius:6,background:inkA(.14),filter:"blur(4px)",maxWidth:320}}/>
        <LockBadge/>
      </div>
    );
  }
  return (
    <div style={{display:"flex",flexDirection:"column",gap:6,padding:mob?"12px 14px":"12px 22px",borderRadius:14,background:C.paper}}>
      <div style={{display:"flex",alignItems:"center",gap:mob?12:18,minHeight:32}}>
        <span className="mono" style={{fontWeight:700,fontSize:14,width:32,flexShrink:0,color:inkA(.62)}}>#{row.rank}</span>
        <span style={{flexGrow:1,fontSize:15,fontWeight:500,minWidth:0}}>{row.name}</span>
        <span className="mono" style={{fontSize:13,flexShrink:0}}>{row.score}/25</span>
        <ScoreBars score={row.score}/>
      </div>
      {unlocked && (
        <div className="mono" style={{fontSize:11,lineHeight:1.5,color:inkA(.62),paddingLeft:mob?0:50}}>
          <span style={{color:C.mintText}}>ANGLE</span> — {row.angle}
        </div>
      )}
    </div>
  );
}

// ─── MAIN PAGE ────────────────────────────────────────────
export default function App() {
  const mob = useIsMobile();
  const [openFaq, setOpenFaq] = useState(0);
  const [unlocked, setUnlocked] = useState(() => {
    try { return localStorage.getItem("ds_board_unlocked") === "1"; } catch { return false; }
  });

  const unlock = () => {
    setUnlocked(true);
    try { localStorage.setItem("ds_board_unlocked", "1"); } catch { /* private mode */ }
  };

  const px = mob ? "18px" : "72px";
  const top = BOARD.top;
  const tailRows = unlocked ? BOARD.rows : BOARD.rows.filter(r => r.rank <= 5 || r.rank >= 9);

  return (
    <div style={{minHeight:"100vh",display:"flex",flexDirection:"column",overflowX:"hidden",background:C.paper,color:C.ink}}>

      {/* NAV */}
      <nav style={{position:"sticky",top:0,zIndex:100,background:"rgba(255,244,233,.92)",backdropFilter:"blur(14px)",borderBottom:`1px solid ${inkA(.08)}`,padding:`0 ${px}`,height:60,display:"flex",alignItems:"center",justifyContent:"space-between"}}>
        <div style={{display:"flex",alignItems:"center",gap:10}}>
          <div style={{width:26,height:26,borderRadius:8,background:C.terminal,display:"flex",alignItems:"center",justifyContent:"center"}}>
            <div style={{width:10,height:10,borderRadius:3,background:C.mint}}/>
          </div>
          <span className="display" style={{fontWeight:700,fontSize:20,letterSpacing:"-0.01em"}}>DropSynth</span>
        </div>
        <div style={{display:"flex",alignItems:"center",gap:mob?12:32}}>
          {!mob && [["How it works","how"],["The board","board"],["Early access","early-access"]].map(([l,id])=>(
            <span key={id} className="hv-link" onClick={()=>smoothScroll(id)} style={{fontSize:14,color:inkA(.78),fontWeight:500}}>{l}</span>
          ))}
          <Btn size="sm" variant="ink" onClick={()=>smoothScroll("early-access")}>{mob?"Get the board":"Get the full board"}</Btn>
        </div>
      </nav>

      {/* HERO */}
      <section style={{position:"relative",overflow:"hidden",background:`linear-gradient(165deg,#FFD3A8 0%,${C.apricot} 60%,#FFB87E 100%)`,padding:`${mob?"48px":"72px"} ${px} ${mob?"56px":"96px"}`}}>
        <div className="ds-blob-a" style={{position:"absolute",top:-120,right:180,width:420,height:420,borderRadius:"50%",background:C.blush,filter:"blur(70px)",opacity:.9}}/>
        <div className="ds-blob-b" style={{position:"absolute",bottom:-140,right:-80,width:380,height:380,borderRadius:"50%",background:C.ember,filter:"blur(80px)",opacity:.35}}/>
        <div className="ds-blob-a" style={{position:"absolute",top:200,left:-140,width:320,height:320,borderRadius:"50%",background:C.blush,filter:"blur(60px)",opacity:.7}}/>
        {!mob && <>
          <div style={{position:"absolute",top:80,right:620,width:90,height:2,background:inkA(.35),transform:"rotate(-32deg)"}}/>
          <div style={{position:"absolute",top:420,right:90,width:60,height:2,background:inkA(.3),transform:"rotate(-32deg)"}}/>
        </>}
        <div style={{position:"relative",display:"grid",gridTemplateColumns:mob?"1fr":"1fr 1fr",gap:mob?40:48,alignItems:"center",maxWidth:1296,margin:"0 auto"}}>
          <div style={{display:"flex",flexDirection:"column",alignItems:"flex-start",gap:mob?20:26}}>
            <div className="ds-rise" style={{animationDelay:"0ms"}}>
              <Eyebrow>EU Trend Board for online sellers</Eyebrow>
            </div>
            <h1 className="display ds-rise" style={{fontSize:mob?40:72,fontWeight:800,lineHeight:1.04,letterSpacing:"-0.02em",animationDelay:"80ms"}}>
              Europe's rising products,{mob?" ":<br/>}ranked every Monday.
            </h1>
            <p className="ds-rise" style={{maxWidth:500,fontSize:mob?16:18,lineHeight:1.55,color:inkA(.78),animationDelay:"160ms"}}>
              DropSynth is an automated product scout. Every Monday it reads supplier bestsellers, TikTok signals, and search trends, then ranks the ten fastest-rising products for EU stores — margin, competition, and the reason, on one board. Free during early access.
            </p>
            <div className="ds-rise" style={{display:"flex",alignItems:"center",gap:20,flexWrap:"wrap",animationDelay:"240ms"}}>
              <Btn size="lg" onClick={()=>smoothScroll("early-access")}>Get the full board</Btn>
              <span className="mono" style={{fontSize:12,letterSpacing:"0.08em",color:inkA(.62),lineHeight:1.6}}>NO CARD. NO SPAM.{mob?" ":<br/>}BOARD UNLOCKS ON THIS PAGE.</span>
            </div>
          </div>
          <div style={{display:"flex",justifyContent:"center"}}>
            <HeroTerminal mob={mob}/>
          </div>
        </div>
      </section>

      <NicheTicker/>

      {/* HOW IT WORKS */}
      <section id="how" style={{padding:`${mob?"56px":"96px"} ${px}`}}>
        <div style={{maxWidth:1296,margin:"0 auto"}}>
          <Reveal>
            <Eyebrow>How it works</Eyebrow>
            <h2 className="display" style={{margin:"14px 0 40px",fontSize:mob?30:44,fontWeight:700,letterSpacing:"-0.015em"}}>One board. Every Monday.</h2>
          </Reveal>
          <div style={{display:"grid",gridTemplateColumns:mob?"1fr":"repeat(3,minmax(0,1fr))",gap:mob?14:24}}>
            {[
              ["01","Scan.","Monday morning. Up to 15 searches across supplier bestsellers, TikTok, search trends, seller communities, marketplace listings.","MONDAYS · 5 SOURCE TYPES"],
              ["02","Score.","Five checks per product: rise speed, margin, competition, EU fit, repeat purchases. Zero to five each. Nothing makes the board on one source.","SCORED 0–25"],
              ["03","Publish.","Top 10 every Monday. Reason it's rising. Risk to watch. One selling angle.","10 PRODUCTS · 2 SIGNALS EACH"],
            ].map(([n,t,d,s])=>(
              <Reveal key={n}>
                <div className="hv-card" style={{display:"flex",flexDirection:"column",gap:14,padding:mob?"24px 22px":30,borderRadius:20,background:C.blush,height:"100%"}}>
                  <span className="mono" style={{fontSize:12,letterSpacing:"0.14em",color:inkA(.62)}}>{n}</span>
                  <div className="display" style={{fontWeight:700,fontSize:22}}>{t}</div>
                  <p style={{fontSize:15,lineHeight:1.55,color:inkA(.78)}}>{d}</p>
                  <div className="mono" style={{fontSize:12,letterSpacing:"0.06em",color:C.mintText,marginTop:"auto"}}>{s}</div>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* THE BOARD */}
      <section id="board" style={{padding:`0 ${px} ${mob?"56px":"96px"}`}}>
        <div style={{maxWidth:1296,margin:"0 auto"}}>
          <Reveal>
            <div style={{borderRadius:20,background:"#FFD9B3",padding:mob?"26px 16px":"44px 48px"}}>
              <div style={{display:"flex",alignItems:"baseline",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}>
                <div style={{display:"flex",flexDirection:"column",gap:8}}>
                  <h2 className="display" style={{fontSize:mob?28:36,fontWeight:700,letterSpacing:"-0.015em"}}>Board 01.</h2>
                  <span className="mono" style={{fontSize:12,letterSpacing:"0.1em",color:inkA(.62)}}>GENERATED THIS MONDAY · {BOARD.week}</span>
                </div>
                {!mob && <span className="mono" style={{fontSize:12,letterSpacing:"0.1em",color:inkA(.62)}}>BOARD {BOARD.week} · MONDAYS</span>}
              </div>

              <div style={{display:"flex",flexDirection:"column",gap:10,marginTop:30}}>
                {/* #1 revealed + expanded */}
                <div style={{display:"flex",flexDirection:"column",borderRadius:14,background:C.paper,overflow:"hidden"}}>
                  <div style={{display:"flex",alignItems:"center",gap:mob?12:18,minHeight:56,padding:mob?"10px 14px":"0 22px",flexWrap:mob?"wrap":"nowrap"}}>
                    <span className="mono" style={{fontWeight:700,fontSize:14,width:32,flexShrink:0}}>#1</span>
                    <span style={{flexGrow:1,fontSize:15,fontWeight:600,minWidth:mob?"100%":0,order:mob?3:0}}>{top.name}</span>
                    <span className="mono" style={{fontSize:13,flexShrink:0}}>{top.score}/25</span>
                    <ScoreBars score={top.score}/>
                  </div>
                  <div className="mono" style={{display:"flex",flexDirection:"column",gap:8,margin:mob?"0 14px 14px":"0 22px 18px",padding:mob?"14px":"16px 18px",borderRadius:12,background:C.paper,border:`1px solid ${inkA(.1)}`,fontSize:12,lineHeight:1.55,color:inkA(.78)}}>
                    <span><span style={{color:C.mintText}}>SIGNALS</span> — {top.signals}</span>
                    <span style={{color:C.mintText}}>{top.margin}</span>
                    <span><span style={{color:C.mintText}}>RISK</span> — {top.risk}</span>
                    <span><span style={{color:C.mintText}}>ANGLE</span> — {top.angle}</span>
                  </div>
                </div>

                {tailRows.filter(r=>r.rank<=5).map(r=><BoardRow key={r.rank} row={r} unlocked={unlocked} mob={mob}/>)}

                {!unlocked && (
                  <div style={{display:"flex",justifyContent:"center",padding:"4px 0"}}>
                    <span className="mono" style={{fontSize:14,color:inkA(.4)}}>· · ·</span>
                  </div>
                )}

                {tailRows.filter(r=>r.rank>5).map(r=><BoardRow key={r.rank} row={r} unlocked={unlocked} mob={mob}/>)}
              </div>

              <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:16,marginTop:26,flexWrap:"wrap"}}>
                <p style={{fontSize:14,color:inkA(.62)}}>
                  {unlocked ? "All ten unlocked. The next board drops Monday." : "Everyone on the list sees all ten, with the reasoning."}
                </p>
                {!unlocked && (
                  <div style={{display:"flex",alignItems:"center",gap:16,flexWrap:"wrap"}}>
                    <span className="mono" style={{fontSize:11,letterSpacing:"0.08em",color:inkA(.62)}}>4 ROWS LOCKED · UNLOCK FREE</span>
                    <Btn onClick={()=>smoothScroll("early-access")}>Get the full board</Btn>
                  </div>
                )}
              </div>
            </div>
          </Reveal>
        </div>
      </section>

      {/* EARLY ACCESS — the terminal returns as a wide card */}
      <section id="early-access" style={{padding:`0 ${px} ${mob?"56px":"96px"}`}}>
        <div style={{maxWidth:880,margin:"0 auto",display:"flex",flexDirection:"column",gap:16}}>
          <Reveal>
            <div style={{borderRadius:16,background:C.terminal,border:`1px solid rgba(0,230,160,.25)`,boxShadow:`0 24px 50px ${inkA(.24)}`}}>
              <MacDots label="EARLY ACCESS" labelColor={C.mint}/>
              <div style={{display:"flex",flexDirection:"column",gap:18,padding:mob?"26px 20px 30px":"36px 40px 40px"}}>
                <h2 className="display" style={{fontSize:mob?26:32,fontWeight:700,letterSpacing:"-0.015em",color:C.paper}}>Free while we build.</h2>
                <p style={{maxWidth:560,fontSize:16,lineHeight:1.55,color:whiteA(.72)}}>
                  The board is free during early access. Early members keep a founder price when the paid board launches.
                </p>
                {unlocked
                  ? <div className="fadeUp" style={{display:"flex",alignItems:"center",gap:14,flexWrap:"wrap",padding:"16px 18px",borderRadius:12,background:whiteA(.05),border:`1px solid rgba(0,230,160,.25)`}}>
                      <span style={{fontSize:15,color:C.paper}}>You're in. All ten rows are unlocked above.</span>
                      <span className="mono" style={{marginLeft:"auto",fontSize:11,letterSpacing:"0.1em",color:C.mint}}>BOARD 01 UNLOCKED</span>
                    </div>
                  : <WaitlistForm onSuccess={unlock}/>
                }
              </div>
            </div>
          </Reveal>
        </div>
      </section>

      {/* FAQ */}
      <section style={{padding:`0 ${px} ${mob?"56px":"96px"}`}}>
        <div style={{maxWidth:1296,margin:"0 auto",display:"grid",gridTemplateColumns:mob?"1fr":"380px minmax(0,1fr)",gap:mob?24:48}}>
          <Reveal>
            <h2 className="display" style={{fontSize:mob?30:44,fontWeight:700,letterSpacing:"-0.015em"}}>Questions.</h2>
          </Reveal>
          <div style={{display:"flex",flexDirection:"column",gap:12}}>
            {FAQS.map((faq,i)=>{
              const open = openFaq===i;
              return (
                <div key={i} className="hv-faq" style={{borderRadius:16,background:open?C.blush:C.paper,border:open?"none":`1px solid ${inkA(.12)}`,overflow:"hidden"}}>
                  <button onClick={()=>setOpenFaq(open?null:i)} style={{width:"100%",minHeight:56,padding:"18px 28px",background:"none",border:"none",display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,cursor:"pointer",color:C.ink,fontSize:mob?15:17,fontWeight:600,fontFamily:"'Space Grotesk',sans-serif",textAlign:"left"}}>
                    <span>{faq.q}</span>
                    <span aria-hidden style={{color:inkA(.6),fontSize:20,flexShrink:0,transform:open?"rotate(45deg)":"none",transition:"transform .2s"}}>+</span>
                  </button>
                  {open && <div className="fadeUp" style={{padding:"0 28px 20px",fontSize:15,color:inkA(.78),lineHeight:1.55}}>
                    {faq.a}{i===FAQS.length-1 && <> <a href="/privacy.html" target="_blank" rel="noreferrer" style={{color:C.mintText}}>Privacy policy</a></>}
                  </div>}
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* FOOTER — the terminal world returns */}
      <footer style={{background:C.terminal,padding:`${mob?"36px":"56px"} ${px}`,display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:20}}>
        <div style={{display:"flex",flexDirection:"column",gap:10}}>
          <span className="mono" style={{fontWeight:700,fontSize:18,color:C.mint}}>DROPSYNTH_</span>
          <a className="mono" href="mailto:hello@dropsynth.app" style={{fontSize:12,color:whiteA(.45)}}>hello@dropsynth.app</a>
        </div>
        <div style={{display:"flex",gap:mob?20:32,fontSize:14,color:whiteA(.65),alignItems:"center",flexWrap:"wrap"}}>
          <a href="/privacy.html" style={{color:whiteA(.65)}}>Privacy</a>
          <a href="mailto:hello@dropsynth.app" style={{color:whiteA(.65)}}>Contact</a>
          <span onClick={()=>smoothScroll("early-access")} style={{color:C.mint,cursor:"pointer"}}>Get the full board</span>
        </div>
      </footer>
    </div>
  );
}
